DailyBugle/DailyBugle/Areas/FrontEnd/Controllers/HomePageController.cs
using DailyBugle.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.UI.HtmlControls;

namespace DailyBugle.Areas.FrontEnd.Controllers
{
    public class HomePageController : Controller
    {
        DailyBugleDBEntities db = new DailyBugleDBEntities();
        private int startIndex = 0;
        private int pageSize = 12;
        // GET: FrontEnd/HomePage

        
        public ActionResult Index(int page=0)
        {
            startIndex = page * pageSize;
            List<News> newsList = db.News.ToList();
            List<NewsViewModel> newsVMList = new List<NewsViewModel>();
            foreach (News news in newsList.Skip(startIndex).Take(pageSize))
            {
                NewsViewModel newsVM = new NewsViewModel()
                {
                NewsId = news.NewsId,
                AuthorName = news.AuthorName,
                Text = news.Text,
                Thumbnail = news.Thumbnail,
                Title = news.Title
                };

            newsVMList.Add(newsVM);
                
            }
            ViewBag.PageCount = (newsList.Count()) / pageSize;
            ViewBag.PageMod = ((newsList.Count() % pageSize) == 0);
            ViewBag.Cat = false;
            return View("Index", newsVMList);
        }

        [ActionName("CatIndex")]
        public ActionResult Index(string CategoryName,int page=0)
        {
            startIndex = page * pageSize;
            List<News> newsList = db.News.Where(m => m.Category == CategoryName).ToList();
            List<NewsViewModel> newsListVM = newsList.Skip(startIndex).Take(pageSize).Select(x => new NewsViewModel
            {
                NewsId = x.NewsId,
                AuthorName = x.AuthorName,
                Category = x.Category,
                Text = x.Text,
                Thumbnail = x.Thumbnail,
                Title = x.Title
            }).ToList();

            ViewBag.PageCount = (newsList.Count()) / pageSize;
            ViewBag.PageMod = ((newsList.Count() % pageSize) == 0);
            ViewBag.Cat = true;
            return View("Index",newsListVM);
        }

        public ActionResult NewsContent(int id)
        {
            News news = db.News.Where(m=> m.NewsId == id).FirstOrDefault();
            NewsViewModel model = new NewsViewModel()
            {
                AuthorName = news.AuthorName,
                NewsId = news.NewsId,
                Text = news.Text,
                Thumbnail = news.Thumbnail,
                Title = news.Title
            };
            ViewBag.Comments = UpdateCommentDB(news.NewsId);
            return View(model);
        }

        public ActionResult SearchNews(string searchText)
        {
            List<News> newsList = new List<News>();
            newsList = db.News.Where(x => x.Title.StartsWith(searchText) ).ToList();
            List<NewsViewModel> newsVMList = new List<NewsViewModel>();
            foreach(var news in newsList)
            {
                NewsViewModel model = new NewsViewModel()
                {
                    AuthorName = news.AuthorName,
                    Category = news.Category,
                    NewsId = news.NewsId,
                    Text = news.Text,
                    Thumbnail = news.Thumbnail,
                    Title = news.Title
                };
                newsVMList.Add(model);
            }
            return View("Index",newsVMList);
        }

        [HttpPost]
        public JsonResult SaveComment(string comment,int id, string personName)
        {
            if (comment.Equals("") || personName.Equals(""))
                return Json("Hata",JsonRequestBehavior.AllowGet);
            News news = db.News.Where(m => m.NewsId == id).FirstOrDefault();
            Comment tmp = new Comment()
            {
                NewsID = id,
                Text = comment,
                PersonName = personName
            };
            db.Comments.Add(tmp);
            db.SaveChanges();
            ViewBag.Comments = UpdateCommentDB(id);
            var JsonModel = new
            {
                Text = comment,
                PersonName = personName
            };
            return Json(JsonModel,JsonRequestBehavior.AllowGet);
        }


        private List<Comment> UpdateCommentDB(int NewsId)
        {
            List<Comment> comments = new List<Comment>();
            foreach (var comment in db.Comments)
            {
                if (comment.NewsID == NewsId)
                    comments.Add(comment);
            }
            return comments;
        }

    }
}

DailyBugle/DailyBugle/Areas/FrontEnd/Views/HomePage/Index.cshtml
@model IEnumerable<DailyBugle.Models.NewsViewModel>

@{
    ViewBag.Title = "View";
    Layout = "~/Areas/FrontEnd/Views/Shared/_LayoutFrontEnd.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/FrontEndHome.css" rel="stylesheet" />
@{
    if (Model.Count() == 0)
    {

        using (Html.BeginForm("SearchNews", "HomePage"))
        {
            <span style="float:right;padding:20px">
                @Html.TextBox("searchText", "", new { placeholder = "Search", required = "required" })
                <button type="submit" class="glyphicon glyphicon-search" style="height:30px;width:50px"></button>
            </span>
        }
        <h1>No News Was Found.</h1>
    }
    else
    {
        <div class="row">
            <div class="col-md-12 text-center">
                @using (Html.BeginForm("SearchNews", "HomePage"))
                {
                    <span style="float:right;padding:20px">
                        @Html.TextBox("searchText", "", new { placeholder = "Search", required = "required" })
                        <button type="submit" class="glyphicon glyphicon-search" style="height:30px;width:50px"></button>
                    </span>
                }
                <div style="margin-top:100px"></div>


                <h1>LATEST NEWS!!!!!</h1>

                @{
                    var first = Model.Max(m => m.NewsId);
                    var news = Model.Where(m => m.NewsId == first).FirstOrDefault();
                    Console.WriteLine(first);
                }
                @{
                    var base64 = Convert.ToBase64String(news.Thumbnail);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                }

                <div class="col-main">

                    <div>
                        <a class="inner" href="@Url.Action("NewsContent","HomePage", new { id=Model.ElementAt(Model.Count()-1).NewsId })">
                            <img src="@imgSrc" style="height:500px;width:800px" />
                            <br />
                            <h3>@news.Title</h3>
                        </a>
                    </div>
                </div>

            </div>
        </div>

        <h1 class="text-center">MORE NEWS!!!!</h1>

        int k = 0;
        while (k < Model.Count())
        {
            <div class="row">
                @while (true)
                {
                    <div class="col-md-4 text-center">
                        @{
                            var base64Col = Convert.ToBase64String(Model.ElementAt(k).Thumbnail);
                            var imgSrcCol = String.Format("data:image/gif;base64,{0}", base64Col);
                        }



                        <div>
                            <a class="inner" href="@Url.Action("NewsContent","HomePage", new { id = Model.ElementAt(k).NewsId})">
                                <img src="@imgSrcCol" style="height:150px;width:200px" />
                                <br />
                                <h4>@Model.ElementAt(k).Title</h4>
                            </a>
                        </div>
                    </div>

                    k++;
                    if ((k % 3 == 0) || (k >= Model.Count()))
                    {
                        break;
                    }
                }
            </div>
        }

            <div class="text-center">
                @{
                    if (ViewBag.PageCount > 0)
                    {
                        for (int i = 0; i < ViewBag.PageCount + 1; i++)
                        {

                            if ((i == ViewBag.PageCount) && ViewBag.PageMod)
                            {
                                break;
                            }
                            if (!ViewBag.Cat)
                            {
                                <a style="font-size:xx-large;padding:10px" href="@Url.Action("Index","HomePage",new { page = i})">@(i + 1)</a>
                            }
                            else
                            {
                                <a style="font-size:xx-large;padding:10px" href="@Url.Action("CatIndex",new {CategoryName = Model.First().Category, page = i})">@(i + 1)</a>
                            }

                        }
                    }

                }
            </div>

    }
}

DailyBugle/DailyBugle/Areas/FrontEnd/Views/HomePage/NewsContent.cshtml
@model DailyBugle.Models.NewsViewModel
@{
    ViewBag.Title = "NewsContent";
    Layout = "~/Areas/FrontEnd/Views/Shared/_LayoutFrontEnd.cshtml";
}
@using System.Web.UI.HtmlControls;
@using DailyBugle.Models
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<div class="newscontent">
    <div class="container">
        @using (Html.BeginForm("SearchNews", "HomePage"))
        {
        <span @*style="float:right;padding:20px"*@ style="margin-left:1200px">
            @Html.TextBox("searchText", "", new { placeholder = "Search", required = "required" })
            <button type="submit" class="glyphicon glyphicon-search" style="height:30px;width:50px"></button>
        </span>
        }
        <div class="row text-center">
            <div class="col-md-12">
                <div class="thumbnail" style="background-color:lightgray">
                    @{
                        var base64 = Convert.ToBase64String(Model.Thumbnail);
                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img src="@imgSrc" />
                    <div class="caption">
                        <h3>@Model.Title</h3>
                        <h4>
                            <span class="glyphicon glyphicon-user">@Model.AuthorName</span>
                        </h4>
                    </div>
                    <p class="text-left" style="padding:50px">
                        @Model.Text
                    </p>
                </div>

            </div>

            <div class="container" id="commentSection" @*style="background-color:lightblue"*@>
                <h2>Comment Section</h2>
                @{
                    foreach (var comment in (ViewBag.Comments as List<Comment>))
                    {
                        <div @*style="border:solid"*@>
                            <h4 style="text-align:left">@comment.PersonName</h4>
                            <p style="text-align:left">@comment.Text</p>
                            <hr style="background-color:darkred;height:3px;color:red;border:none" />
                        </div>
                    }
                }
            </div>

        </div>

        <form id="commentform" style="margin-left:50px;border:solid">
            <textarea placeholder="Comment Text" rows="4" cols="1000" form="commentform" id="txtcomment" name="txtcomment" required></textarea>
            <br />
            <input placeholder="Your Name" id="txtperson" name="txtperson" required/>
            <input type="button" id="button" name="button" value="Post Comment" />
            
        </form>
    </div>
</div>

<script type="text/javascript">

    $("#button").click(function () {
        $.ajax({
            @*url: '@Url.Action("SaveComment","HomePage", new { area="FrontEnd"})',*@
            url: "/FrontEnd/HomePage/SaveComment",
            type: "POST",
            data: { comment: $("textarea#txtcomment").val(), id: @Model.NewsId, personName: $("input#txtperson").val() },
            dataType: "json",
            success: function (tmp) {
                if (tmp == "Hata") {
                    console.log(document.getElementById("txtwarning"));
                    if (!document.getElementById("txtwarning")) {
                        var warningText = document.createElement("label");
                        warningText.id = "txtwarning";
                        warningText.innerHTML = "Please fill the empty spaces."
                        warningText.style.color = 'red';
                        document.getElementById("commentSection").appendChild(warningText);
                    }
                    
                }
                else {
                    if (document.getElementById("txtwarning"))
                        document.getElementById("txtwarning").remove();
                    console.log(tmp);
                    //alert("hello");
                    var commentdiv = document.createElement("div");
                    var personText = document.createElement("h4");
                    var commentText = document.createElement("p");
                    var hr = document.createElement("hr");
                    personText.style.textAlign = commentText.style.textAlign = 'left';
                    hr.style.backgroundColor = 'darkred';
                    hr.style.height = '3px';
                    hr.style.border = 'none';

                    personText.innerHTML = tmp.PersonName;
                    commentText.innerHTML = tmp.Text;

                    commentdiv.appendChild(personText);
                    commentdiv.appendChild(commentText);
                    commentdiv.appendChild(hr);
                    document.getElementById("commentSection").appendChild(commentdiv);
                    console.log(document.getElementById("txtperson").value);
                    document.getElementById("txtperson").value = "";
                    document.getElementById("txtcomment").value = "";
                }
                
            },
            error: function (error) {
                console.log(error);
                alert("error");
            }
        });
    });

</script>