DailyBugle/DailyBugle/Areas/Admin/Controllers/AdminPageController.cs
using DailyBugle.Areas.Admin.Models;
using DailyBugle.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DailyBugle.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AdminPageController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/AdminPage

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRole(FormCollection form)
        {
            string roleName = form["txtRoleName"];
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));

            if (!roleManager.RoleExists(roleName))
            {
                //create role
                var role = new IdentityRole(roleName);
                roleManager.Create(role);

            }
            return View("Index");
        }

        public ActionResult CreateCategory()
        {
            ViewBag.AlreadyExists = false;
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategory(FormCollection form)
        {
            DailyBugleDBEntities db = new DailyBugleDBEntities();
            string categoryName = form["txtCategoryName"];
            ViewBag.AlreadyExists = false;
            foreach (var cat in db.Categories)
            {
                if (cat.Name.Equals(categoryName))
                {
                    ViewBag.AlreadyExists = true;
                    return View();
                }
            }
            Category category = new Category();
            category.Name = categoryName;
            db.Categories.Add(category);
            db.SaveChanges();

            return View();
        }

        public ActionResult AssignRole()
        {
            ViewBag.Roles = context.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View();
        }

        [HttpPost]
        public ActionResult AssignRole(FormCollection form)
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            string email = form["txtEmail"];
            string roleName = form["txtRoleName"];
            ApplicationUser user = context.Users.Where(x => x.Email.Equals(email, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            if (user == null)
            {
                BoolModel b1 = new BoolModel() { result = false };
                ViewBag.Roles = context.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
                return View(b1);
            }

            string ErrorInput = form["ErrorInput"];
            
            if ( roleName!="")
            {
                userManager.AddToRole(user.Id, roleName);
                return RedirectToAction("Index");
            }
            BoolModel b2 = new BoolModel() { result = true };
            ViewBag.Roles = context.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View(b2);

        }
        
        [HttpPost]
        public ActionResult ValidateEmail(string data)
        {
            bool result;
            ApplicationUser user = context.Users.Where(x => x.Email.Equals(data, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            if (user == null)
                result = false;
            else
                result = true;
            return View(result);
        }
    }
}

DailyBugle/DailyBugle/Areas/Admin/Views/AdminPage/AssignRole.cshtml
@model DailyBugle.Areas.Admin.Models.BoolModel
@{
    ViewBag.Title = "AssignRole";
}

<h2>AssignRole</h2>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>

@using (Html.BeginForm("AssignRole", "AdminPage", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <label class="control-label">Email</label>
            <input type="text" name="txtEmail" class="form-control" required />
            @if (Model != null && Model.result == false)
            {
                @: Please enter a valid email
            }
        </div>
        <div class="col-md-6">
            <label class="control-label">Select a Role</label>
            @Html.DropDownList("txtRoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select...")
            @*<p class="form-control" name="roleError" id="roleError" style="color:red"></p>*@
            @if(Model !=null && Model.result == true)
            {
                @: Please select a role
            }
            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-1 lg-12">
            <button onclick="emre()" value="Submit" type="submit"class="btn btn-primary">Save</button>

        </div>
    </div>
}

<script>
    function emre() {
        console.log(document.getElementsByTagName("select")[0].value);
        if (document.getElementsByTagName("select")[0].value == "") {
            //alert("Please select a role");
            document.getElementById("roleError").innerHTML = "Please select a role";
            @*document.getElementById("ErrorInput").innerHTML = "a";
            @Html.ViewBag.errorMessage = true;*@
        }
        //else
        //    document.getElementById("ErrorInput").innerHTML = "";
            //console.log("true");

    }

    @*function ValidateEmail() {
        $.ajax({
            type: 'POST',
            url: "@Url.Content("/AdminPage/ValidateEmail/")",
            data: document.getElementsByTagName("input")[0].value,
            dataType: datatype,
            success: function (result) {

            }
        })
    }*@
</script>

DailyBugle/DailyBugle/Areas/Admin/Views/AdminPage/CreateCategory.cshtml
@model DailyBugle.Models.Category
@{
    ViewBag.Title = "CreateCategory";
}

<h2>CreateCategory</h2>

@using (Html.BeginForm("CreateCategory", "AdminPage", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <label class="control-label">Category Name</label>
            <input class="form-control" type="text" name="txtCategoryName" required />
            @{ 
                if (ViewBag.AlreadyExists)
                {
                    <label style="color:red" class="has-error">The Category Already Exists</label>
                }
            }
        </div>
    </div>
    <div class="row">
        <button type="submit" value="Submit" class="btn btn-primary">Save</button>
    </div>

}

DailyBugle/DailyBugle/Areas/Admin/Views/AdminPage/CreateRole.cshtml
@{
    ViewBag.Title = "CreateRole";
}

<h2>CreateRole</h2>

@using (Html.BeginForm("CreateRole", "AdminPage", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-6">
            <label class="control-label">Role Name</label>
            <input class="form-control" type="text" name="txtRoleName" required/>
        </div>
    </div>
    <div class="row">
        <button type="submit" value="Submit" class="btn btn-primary">Save</button>
    </div>

}

DailyBugle/DailyBugle/Areas/Admin/Views/AdminPage/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<ul>
    <li>@Html.ActionLink("Assign Role","AssignRole","AdminPage")</li>
    <li>@Html.ActionLink("Create Role","CreateRole","AdminPage")</li>
    <li>@Html.ActionLink("Edit Profile","EditProfile",new { area = "", controller = "User" })</li>
    <li>@Html.ActionLink("Create Category","CreateCategory","AdminPage")</li>
</ul>